### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by zwells** [danrubel/rpi_i2c.dart#3]
I'm running my flutter app on Android on the Pi4.  Will this work on Android 10 or was it designed for flutter-pi.

Thanks.

**Comment by danrubel** [comment]
This is designed to run with Dart on the Raspberry Pi.
It should work with Flutter on the Raspberry Pi since Flutter is based on Dart, but I have never tried it.
I don't think it will run with Flutter on any phone since the code is specific to Raspberry Pi.

**Comment by zwells** [comment]
Great, thanks for the quick reply.  I will give it a try in the near future.
